### ISSUE TITLE
Add some kind of testing infratructure

### ISSUE THREAD

**Issue by ludat** [ludat/dottle#6]
I don't know if there is someone that provides a way to test different (and probably old) environments. Also normal unit testing to check functions do what they should, https://github.com/mlafeldt/sharness seems like a good option.

@romanblanco do you know any other framework like sharness or providers of a travis-like service?

**Comment by romanblanco** [comment]
@ludat unfortunately, I'm not familiar with any unix specs framework, can't help here

**Comment by ludat** [comment]
BTW @romanblanco if you want some feature just add an issue and tag it as `enhancement`

It could be something very easy to implement that I didn't think of or that I don't need right now.

**Comment by ludat** [comment]
Options:
- **[cram](https://bitbucket.org/brodie/cram)**: written in python and a little unmaintained but the architecture is very declarative and clear.
- **[sharness](https://github.com/mlafeldt/sharness)**: written in posix shell but a lot less expressive. Only has normal asserts and some kind of isolation.
- **[rnt](https://github.com/roman-neuhauser/rnt)**: Mixes the best of both... it's quite declarative and it doesn't use python... It probably has some bashisms but nothing that can't be fixed. Probably I'll chose this one.

**Comment by ludat** [comment]
Fixed :D
